// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Personalized product recommendations based on user history.
 *
 * - getPersonalizedRecommendations - A function that returns product recommendations.
 * - PersonalizedRecommendationsInput - The input type for the getPersonalizedRecommendations function.
 * - PersonalizedRecommendationsOutput - The return type for the getPersonalizedRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedRecommendationsInputSchema = z.object({
  userId: z.string().describe('The ID of the user.'),
  browsingHistory: z.array(z.string()).describe('The user browsing history as a list of product IDs.'),
  purchaseHistory: z.array(z.string()).describe('The user purchase history as a list of product IDs.'),
  wishlist: z.array(z.string()).optional().describe('The user wishlist as a list of product IDs.'),
  numRecommendations: z.number().default(5).describe('The number of product recommendations to return.'),
});

export type PersonalizedRecommendationsInput = z.infer<typeof PersonalizedRecommendationsInputSchema>;

const PersonalizedRecommendationsOutputSchema = z.object({
  productIds: z.array(z.string()).describe('A list of recommended product IDs.'),
});

export type PersonalizedRecommendationsOutput = z.infer<typeof PersonalizedRecommendationsOutputSchema>;

export async function getPersonalizedRecommendations(input: PersonalizedRecommendationsInput): Promise<PersonalizedRecommendationsOutput> {
  return personalizedRecommendationsFlow(input);
}

const productRecommendationPrompt = ai.definePrompt({
  name: 'productRecommendationPrompt',
  input: {
    schema: PersonalizedRecommendationsInputSchema,
  },
  output: {
    schema: PersonalizedRecommendationsOutputSchema,
  },
  prompt: `You are a personal shopping assistant for a classic-style e-commerce store.
  Based on the user's browsing history, purchase history, and wishlist, recommend {{numRecommendations}} products that they might be interested in.

  Browsing History: {{browsingHistory}}
  Purchase History: {{purchaseHistory}}
  Wishlist: {{wishlist}}

  Return a list of product IDs.
  `,
});

const personalizedRecommendationsFlow = ai.defineFlow(
  {
    name: 'personalizedRecommendationsFlow',
    inputSchema: PersonalizedRecommendationsInputSchema,
    outputSchema: PersonalizedRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await productRecommendationPrompt(input);
    return output!;
  }
);
